### ISSUE TITLE
How to translate use mdbook-i18-helper to update .po file ?

### ISSUE THREAD

**Issue by Demian101** [zkp-co-learning/zkp-co-learning.github.io#20]
related issue: https://github.com/r12f/potr/issues/7

-----

感谢，我发现 openai 目前的接口限制好像是 3QPM (3 Queries per minute)

一章一章的来确实会好很多，步骤大概就是 :

1. 新建一个 `temp` mdbook 文件夹
2. 把 `要翻译的章节` 和 `summary.md` 单独放到 ./src
3. 使用 mdbook-i18n-helpers 的命令 update `message.pot`

```bash
MDBOOK_OUTPUT='{"xgettext": {"pot-file": "messages.pot"}}' \
  mdbook build -d po
```

4. 使用 [potr](https://github.com/r12f/potr) 进行翻译，可以使用 potr 提供的 filter 命令过滤缩小翻译范围

```rust
potr -p po/en1.po -e openai -t en -k  sk-wrv....fcs  --code
```

5. 手动逐个检查 en.po 更新的 `#, fuzzy` 条目来 review 翻译质量  *[un support]*

**Comment by Demian101** [comment]
> [github](https://github.com/zkp-co-learning) of $\mathcal{Z}_2 \mathbb{O} \ {\text -} \ \mathcal{K}_7 \mathbb{E}$


### <span style="color: grey;">**Welcome to the**</span>

![](logo.png)



### <span style="color: grey;">**World!**</span>



<br />

#### [🔍 How to contribute?](./how-to-contribute.md)

<br />

<br />

------

[TOC]

------




<br />

<br />

## 📖 What is [z2o-k7e](https://learn.z2o-k7e.world)?

[z2o-k7e](https://learn.z2o-k7e.world) is a community-driven project dedicated to collaborative ZKP (Zero-Knowledge Proof) studies and creation. In three terms zkp learning journey since February 2023, we've explored resources like <https://www.zkiap.com>, <https://zk-learning.org>, [write PLONK protocol with plonkathon](https://github.com/0xPARC/plonkathon) , and [0xPARC halo2 lectures](ongoing now), engaging with over 300 enthusiastic participants.

In this journey, our vibrant community learns collectively, assists one another with q-a, and write zkp-related content collaboratively.

At [z2o-k7e](https://learn.z2o-k7e.world), we award bounties to motivate learners for their tech insights, encourage active community maintenance, and promote the organization of ZKP-centric knowledge. Collectively, our mission is to enhance the quality of **ZKP Public Goods**.

🚀 Now we're gearing up to roll out advanced content for zk-learning.org, including intriguing topics like Nova, STARK, and beyond.

<br />

<br />


## 🚩 Problem Statement:

The world of ZKP is riddled with challenges - so many noises, steep entry barriers, convoluted learning processes, an absence of dedicated learning communities, and a deluge of often nebulous information. Through **[z2o-k7e](https://learn.z2o-k7e.world)** & zkp-colearning community, we're committed to confronting and tackling these issues head-on.

<br />

<br />


## 🌟 Core Contributors

- **Dr. Qi Zhou**: Founder of [ETHStorage](https://eth-store.w3eth.io)
- **Yu Guo@Secbit**: Founder of [Secbit](https://secbit.io/), <https://github.com/sec-bit>, author of [understanding PLONK series](https://learn.z2o-k7e.world/plonk-intro-cn/plonk-intro.html)
- **[Kurt Pan](https://cryptography.land/)**: Ph.D. in Cryptography from Fudan University, <https://github.com/kurtpan666>
- **Shirlene 孝羽**: director of Creators Colearning Community
- **[Demian](https://github.com/Demian101)**: [z2o-k7e](https://learn.z2o-k7e.world) core contributor, zkp-colearning maintainer
- **Harry L**: co-Founder of Rebase Community, Core Contributor of @Antalpha_Labs.
- Our Maintainers: **dream@Scroll, Po@EthStorage, 0xhhh@EthStorage, 周洋(Yang Zhou), 啊咪咪小熊, 张康 Daniel, Frank Jz Liu, miles, 白菜, KEEP, CJ, 笃行, 阳小雪, , 饭卡里还有不少钱呢...**

<br />

<br />


## 🚀 Vision & Mission:

0. Build a better, more accessible, and more extensive zkp tutorial series as a public good
1. Continue to recruit Maintainers to collaboratively manage the community and answer questions.
2. Operate technical media and Twitter to expand influence.
3. Utilize zk technology to support a broader range of web3 applications. 

<br />

<br />

## 📅 Roadmap:

Our aspirations for the next 6 months (culminating in ~12/2023) are:

 - [x] 1. Launch the [learn.z2o-k7e.world](learn.z2o-k7e.world) website and aim for:
 - [x]   1.1 Comprehensive ZKP learning path sorting and a clear, seamless learning guide. 
 - [x]   1.2. Building amazing [halo2 Course](https://learn.z2o-k7e.world/halo2/halo2.html) to help zkers to write zkp circuits
 - [ ] 2. Develop at least one zk application project with specific needs and use cases.
 - [x] 3. Organize and open-source the vast amount of zk materials that have accumulated and scattered within the current colearning GROUP.
 - [ ] 4. Attract at least 200 more people to participate in zkp technology learning and engage at least 20 developers in the development of zkp projects.
